### ISSUE TITLE
How to install Patzilla on Ubuntu 23.04 ?

### ISSUE THREAD

**Issue by thomas2net** [ip-tools/patzilla#73]
Hello,

I have failed to install using docker, docker-compose, or Linux installation following instructions at [Installation on Linux or macOS](https://docs.ip-tools.org/patzilla/install/linux-macos.html#install-linux-macos). Does anyone have step-by-step instructions for installing that work for Ubuntu 23.04?

To install using Docker, phantomjs being unavailable, I deleted the phantomjs entry in dockerfile and added instructions found at [Installing phantomjs with node in docker](https://stackoverflow.com/questions/39451134/installing-phantomjs-with-node-in-docker).

However, if I run
```shell
docker run --rm -it --volume=$PWD/Downloads/patzilla/docker/patzilla.ini:/etc/patzilla.ini:ro --publish=6543:6543 local/patzilla pserve /etc/patzilla.ini
```

I get:
```python
Traceback (most recent call last):
  File "/usr/local/bin/pserve", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pyramid/scripts/pserve.py", line 32, in main
    return command.run()
  File "/usr/local/lib/python2.7/dist-packages/pyramid/scripts/pserve.py", line 168, in run
    loader.setup_logging(config_vars)
  File "/usr/local/lib/python2.7/dist-packages/plaster_pastedeploy/__init__.py", line 221, in setup_logging
    if "loggers" in self.get_sections():
  File "/usr/local/lib/python2.7/dist-packages/plaster_pastedeploy/__init__.py", line 58, in get_sections
    parser = self._get_parser()
  File "/usr/local/lib/python2.7/dist-packages/plaster_pastedeploy/__init__.py", line 241, in _get_parser
    loader = loadwsgi.ConfigLoader(self.uri.path)
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 399, in __init__
    with open(filename) as f:
IOError: [Errno 21] Is a directory: '/etc/patzilla.ini'
```

Trying with "docker-compose up" I get:
```
Creating network "docker_patzilla_net" with the default driver
Pulling mongodb (mongo:4-focal)...
4-focal: Pulling from library/mongo
7a2c55901189: Pull complete
b57cf58c4ffe: Pull complete
5bb145f2aa46: Pull complete
93f83d52d64e: Pull complete
5e012812179b: Pull complete
a6343ab9f99f: Pull complete
db691c26a2f1: Pull complete
5309bfc44820: Pull complete
6fb4bc4192f3: Pull complete
Digest: sha256:37f5e457e8ee72f3292cfe3177ace93c9bad7f84cdacd96fe6f82093b748c637
Status: Downloaded newer image for mongo:4-focal
Building patzilla
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Sending build context to Docker daemon  13.97MB
Step 1/24 : FROM debian:bullseye-slim AS patzilla-baseline
 ---> 06a976e818e6
Step 2/24 : RUN     apt-get update &&     apt-get install --yes     wget     build-essential     python2     python2-dev     libjpeg-dev     libfreetype-dev     liblcms2-dev     libtiff-dev     libffi-dev     libssl-dev     libxml2-dev     libxslt1-dev     zlib1g-dev     pdftk     poppler-utils     imagemagick     libtiff-tools     libreoffice     unoconv     fontconfig libfontconfig libfreetype6     &&     wget https://bootstrap.pypa.io/pip/2.7/get-pip.py &&     python2 get-pip.py &&     rm -rf /var/cache/apt
 ---> Using cache
 ---> f85aacabe89e
Step 3/24 : FROM patzilla-baseline
 ---> f85aacabe89e
Step 4/24 : RUN     pip install patzilla &&     rm -r /root/.cache
 ---> Using cache
 ---> dcd8ed05c6d5
Step 5/24 : FROM ubuntu:latest
 ---> e4c58958181a
Step 6/24 : WORKDIR /opt/backend
 ---> Using cache
 ---> bb9b7cd2c2b0
Step 7/24 : RUN su -
 ---> Using cache
 ---> daba71ff9b35
Step 8/24 : RUN  apt-get update
 ---> Using cache
 ---> 457f76b0ddfd
Step 9/24 : RUN apt-get install sudo -y
 ---> Using cache
 ---> 8f4a1e3daa77
Step 10/24 : RUN sudo apt install curl -y
 ---> Using cache
 ---> e50a8baa85c1
Step 11/24 : RUN curl -sL https://deb.nodesource.com/setup_17.x -o nodesource_setup.sh
 ---> Using cache
 ---> f38875c9174a
Step 12/24 : RUN sudo bash nodesource_setup.sh
 ---> Running in d084f29c8ea9
```

```
================================================================================
================================================================================

                              DEPRECATION WARNING                            

  Node.js 17.x is no longer actively supported!

  You will not receive security or critical stability updates for this version.

  You should migrate to a supported version of Node.js as soon as possible.
  Use the installation script that corresponds to the version of Node.js you
  wish to install. e.g.

   * https://deb.nodesource.com/setup_16.x — Node.js 16 "Gallium"
   * https://deb.nodesource.com/setup_18.x — Node.js 18 LTS "Hydrogen" (recommended)
   * https://deb.nodesource.com/setup_19.x — Node.js 19 "Nineteen"
   * https://deb.nodesource.com/setup_20.x — Node.js 20 "Iron" (current)

  Please see https://github.com/nodejs/Release for details about which
  version may be appropriate for you.

  The NodeSource Node.js distributions repository contains
  information both about supported versions of Node.js and supported Linux
  distributions. To learn more about usage, see the repository:
    https://github.com/nodesource/distributions

================================================================================
================================================================================

Continuing in 20 seconds ...


================================================================================
▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
================================================================================

                           SCRIPT DEPRECATION WARNING                    

  
  This script, located at https://deb.nodesource.com/setup_X, used to
  install Node.js is deprecated now and will eventually be made inactive.

  Please visit the NodeSource distributions Github and follow the
  instructions to migrate your repo.
  https://github.com/nodesource/distributions

  The NodeSource Node.js Linux distributions GitHub repository contains
  information about which versions of Node.js and which Linux distributions
  are supported and how to install it.
  https://github.com/nodesource/distributions


                          SCRIPT DEPRECATION WARNING

================================================================================
▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
================================================================================

TO AVOID THIS WAIT MIGRATE THE SCRIPT
Continuing in 60 seconds (press Ctrl-C to abort) ...


## Installing the NodeSource Node.js 17.x repo...


## Populating apt-get cache...

+ apt-get update
Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [109 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1400 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1274 kB]
Fetched 3012 kB in 2s (1863 kB/s)
Reading package lists...

## Installing packages required for setup: lsb-release gnupg...

+ apt-get install -y lsb-release gnupg > /dev/null 2>&1

## Confirming "jammy" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_17.x/dists/jammy/Release'

## Your distribution, identified as "jammy", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

The command '/bin/sh -c sudo bash nodesource_setup.sh' returned a non-zero code: 1
ERROR: Service 'patzilla' failed to build : Build failed
```

When installing using https://docs.ip-tools.org/patzilla/install/linux-macos.html#install-linux-macos
I get various mixups between python 2.7 and python 3. 

Help is welcome!

**Comment by amotl** [comment]
Dear Thomas,

thank you for writing in, and apologies for the late reply. Unfortunately, PatZilla is based on Python 2 up until now, we dearly need to converge GH-70 to improve that situation.

Are you still interested in using PatZilla?

In general, the JavaScript installation is only needed in development mode, in order to build the frontend. The `patzilla` package on PyPI includes the frontend bundle, so it should be ready to work after using `pip install patzilla`. I didn't build the Docker image for quite some time already, so apologies again if there are any hiccups.

With kind regards,
Andreas.

**Comment by jhannink** [comment]
Any plans on bringing this back to life? I am struggling as well with getting this running in docker.

Looks like a great tool that 🚀

**Comment by amotl** [comment]
Hi @jhannink. Thank you for signalling interest. We will try to make a difference in 2025, but I can't share any estimate ;].
